<?php
$num = 1;
?>
<h3>All tables</h3>
<table cellpadding="0" cellspacing="0" class="content-table">
    <thead>
        <tr>
            <td></td>
            <td><b>Name</b></td>
            <td><b>Added</b></td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->tables as $t): ?>
            <tr class="id_field" id="id_field15">
                <td><?php echo $num++ ?></td>
                <td>                    
                    <a href="/admin-tables/view-table/id_table/<?php echo $t->id_table ?>">
                        <?php echo ucwords($t->name)?>
                    </a>
                </td>
                <td class="action">
                    <a><?php echo $t->created ?></a>
                </td>
            </tr>          
            <?php
        endforeach;
        ?>
    </tbody>
</table>