<div id="main">
    <table cellpadding="0" cellspacing="0">
<!--        <tbody>
        <tr>
            <td><b><?php echo $this->translate('Field name') ?></b></td>
            <td><b><?php echo $this->translate('Field type') ?></b></td>
            <td><b><?php echo $this->translate('Primary') ?></b></td>
            <td><b><?php echo $this->translate('Required') ?></b></td>
            <td><b><?php echo $this->translate('Edit field') ?></b></td>
            <td><b><?php echo $this->translate('Delete field') ?></b></td>
        </tr>-->
        <?php foreach ($this->tables as $t): ?>
            <tr>
                <td><a href="/admin-tables/view-table/id_table/<?php echo $t->id_table?>"><?php echo $t->name ?></a></td>
            </tr>          
            <?php
        endforeach;
        ?>   
<!--        </tbody>-->
    </table>
</div>