<div>
    <table>
        <tr>
            <?php
            foreach($this->fields as $f):?>
            <th><?php echo $f?></th>
            <?php
            endforeach;
            ?>
        </tr>
    <?php
    foreach($this->tableItemsPaginator as $i):?>
    <tr>
        <?php
        foreach($i as $k => $v):?>
        <td><?php echo $v?></td>
        <?php
        endforeach;
        ?>
    </tr>
    <?php
    endforeach;
    ?>
    </table>
    <?php echo $this->paginationControl($this->tableItemsPaginator, 'Sliding', '/common/paginator.phtml')?>
    <div>
        <a href="/admin/add-item/id-table/<?php echo $this->table->id_table?>">
            Add item in table <?php echo ucfirst($this->table->name)?>
        </a>
    </div>
</div>