<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Transdmin Light</title>

        <!-- CSS -->
        <link href="/css/transdmin.css" rel="stylesheet" type="text/css" media="screen" />
        <!--[if IE 6]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie6.css" /><![endif]-->
        <!--[if IE 7]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie7.css" /><![endif]-->

        <!-- JavaScripts-->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
        <?php echo $this->headScript()?>
        <script type="text/javascript" src="/js/admin.js"></script>
    </head>

    <body>
        <div id="wrapper">
            <h1><a href="/admin"><span class="blue">Ad</span><span class="red">min</span> <span class="weekGray">Light</span></a></h1>

            <?php echo $this->mainNav()?>

            <div id="containerHolder">
                <div id="container">
                    <?php echo $this->sidebar()?>
                    
                    <!-- h2 stays for breadcrumbs -->
                    <?php echo $this->breadcrumbs()?>
                    <div id="main">
                        <?php echo $this->layout()->content?>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>	

            <p id="footer"></p>
        </div>
        <!-- // #wrapper -->
    </body>
</html>


